LIPs/LIP-poll-based-governance.md

This is the parent LIP for poll based governance that bundles LIP-15 and LIP-16.

Poll based governance

---

LIPs/LIP-15.md

Assign LIP-15 Last Call status.

LIP-15: Assign Last Call

---

LIPs/LIP-16.md

Assign LIP-16 Last Call status.

LIP-16: Assign Last Call

---

LIPs/LIP-19.md

Assign LIP-19 Last Call status.

LIP-19: Assign Last Call

---

LIPs/LIP-16.md

Accept a choiceID when voting with the poll contract with the valid list of choiceIDs defined by the off-chain indexer. This update makes it easier to add additional voting choices in the future if needed without requiring a contract update.

LIP-16: Update poll contract to accept choiceID

---

LIPs/LIP-15.md

LIP-15: Assign Proposed

---

LIPs/LIP-16.md

- Use QUOTA instead of THRESHOLD
- Assign LIP-16 Proposed status

LIP-16: Assign Proposed

---

LIPs/LIP-19.md

LIP-19: Assign Proposed

---

LIPs/LIP-1.md
LIPs/LIP-15.md
LIPs/LIP-16.md
LIPs/LIP-19.md

9b258ec
**LIP-15, LIP-16, LIP-19: Assign Accepted status**
Based on results of poll 0x6bbac22e3766aa76956038a101b96ca4fcb28964 on
Ethereum mainnet.
dd7352a
**LIP-15, LIP-16, LIP-19: Assign Final status**
75f5508
**LIP-1: Update based on LIP-15**

LIP-15, LIP-16, LIP-19: Assign Final status

---

LIPs/LIP-25.md

Update the spec to reflect the latest implementation details in https://github.com/livepeer/protocol/pull/383

LIP-25: update spec with additional details

---

LIPs/LIP-25.md

This PR assigns last call for LIP-25

LIP-25: assign last call

---

LIPs/LIP-snapshot_earnings.md

This PR adds a draft proposal for https://github.com/livepeer/LIPs/issues/52

LIP-52 draft

---

LIPs/LIP-52.md

LIP-52: last call

---

LIPs/LIP-36.md

Based on poll
https://etherscan.io/address/0x87c065424333a7a1ae05fd7dbfb27e5741168038

Assign LIP-36 Accepted

---

LIPs/LIP-52.md

Move LIP-52 into accepted status

LIP-52: accepted status

---

LIPs/LIP-25.md

- Update delay period
- Move to proposed

LIP-25: proposed

---

LIPs/LIP-25.md

Result of the poll
https://explorer.livepeer.org/voting/0xbc2ea5527586346bde95136c3ea99d699d55443c

LIP-25 assign Accepted

---

LIPs/LIP-73.md
README.md

Poll that accepted LIP-73 https://explorer.livepeer.org/voting/0xd00a506956896c8dfd5dfed0133f870cbe8e49f2

LIP-73: Assign Accepted

---

LIPs/LIP-73.md

As stated in the commit message, just a few minor adjustments to correct LIP-73's typos

LIP-73: Added minor updates to fix a few typos

---

LIPs/LIP-83.md
README.md

Assigning LIP-83 as Proposed because the Last Call period that was started by https://github.com/livepeer/LIPs/pull/84 is over and @0xVires indicated (offline) that he is comfortable with moving forward with a poll.

LIP-83: Assign Proposed

---

LIPs/LIP-83.md
README.md

LIP-83 was accepted by the community in this poll https://explorer.livepeer.org/voting/0x84618441dbe2b0ada3dff046e9d9472254a1b92d.

LIP-83: Assign Accepted

---

LIPs/LIP-83.md
README.md

The staged Governor update was executed in https://arbiscan.io/tx/0xf07bdc4756cdf96d225600c8369056bb7ddea373e6dc565e9db03a9fd2a2b1e2.

LIP-83: Assign Final

---

LIPs/LIP-89.md
LIPs/LIP-livepeer_treasury.md
assets/treasury_technical_spec.md

This includes an LIP for creation of an onchain Livepeer treasury, and an accompanying technical spec. It is part of a bundle which encompasses one additional LIP and the bundle LIP to be PR'd separately.

Livepeer treasury LIP and spec

---

LIPs/LIP-90.md
LIPs/LIP-funding_entity_conventions.md

LIP for social conventions for the types of special purpose entities that the treasury is designed to fund.

LIP for funding entity conventions as part of the treasury bundle.

---

LIPs/LIP-92.md

Reported on: https://github.com/code-423n4/2023-08-livepeer-findings/issues/209

LIP-92: Fix a couple of typos

---

LIPs/LIP-89.md
LIPs/LIP-90.md
LIPs/LIP-91.md
LIPs/LIP-92.md

Do 89 and 90 move to Proposed as well, or sit in Last Call so that only the bundle can be proposed?

Moving Delta LIPs to Proposed
